### ISSUE TITLE
Compiler crash when ContributesBinding boundType has type parameters

### ISSUE THREAD

**Issue by eygraber** [amzn/kotlin-inject-anvil#97]
If I have an interface with type parameters:

```kotlin
interface Foo<T, R>
```
and I use `ContributesBinding` on a concrete implementation of it:

```kotlin
class Bar
class Baz

@ContributesBinding(MyScope::class)
class RealFoo : Foo<Bar, Baz>
```

I get the following crash:

```
[ksp] java.lang.IllegalStateException: KSType 'Foo<Bar, Baz>' has type arguments, which are not supported for ClassName conversion. Use KSType.toTypeName().
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toClassName(KsTypes.kt:44)
	at software.amazon.lastmile.kotlin.inject.anvil.processor.ContributesBindingProcessor$GeneratedFunction.bindingMethodReturnType_delegate$lambda$0(ContributesBindingProcessor.kt:220)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at software.amazon.lastmile.kotlin.inject.anvil.processor.ContributesBindingProcessor$GeneratedFunction.getBindingMethodReturnType(ContributesBindingProcessor.kt:219)
	at software.amazon.lastmile.kotlin.inject.anvil.processor.ContributesBindingProcessor.generateComponentInterface(ContributesBindingProcessor.kt:93)
	at software.amazon.lastmile.kotlin.inject.anvil.processor.ContributesBindingProcessor.process(ContributesBindingProcessor.kt:72)
	at software.amazon.lastmile.kotlin.inject.anvil.CompositeSymbolProcessor.process(CompositeSymbolProcessor.kt:17)
```

**Comment by vRallev** [comment]
We should make this work, but it will start to fail if there are multiple super types:
```kotlin
@ContributesBinding(MyScope::class)
class RealFoo : Foo<Bar, Baz>, SecondSuperType
```
In this case you have to use the `boundType` parameter, but with that you cannot specify the type parameters:
```kotlin
@ContributesBinding(MyScope::class, boundType = Foo::class)
class RealFoo : Foo<Bar, Baz>, SecondSuperType
```
